server:
  port: 8080

spring:
  datasource:
    username: root
    password: ya78yrc8n4w3984
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true
    hibernate:
      ddl-auto: validate
    show-sql: false
indexing-settings:
  sites:
    - url: https://www.svetlovka.ru/
      name: Светловка.ру
    - url: https://www.playback.ru
      name: PlayBack.Ru
  user-agent: HeliontSearchBot
  referrer: http://www.google.com
