server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: OFF
indexing-settings:
  sites:
    - url: https://www.svetlovka.ru/
      name: Светловка.ру
    - url: https://www.playback.ru
      name: PlayBack.Ru
  user-agent: HeliontSearchBot
  referrer: http://www.google.com
